apiVersion: v1
kind: Service
metadata:
  name: java-project
spec:
  selector:
    name: time-provider-DNS-service
  clusterIP: None
  ports:
  - name: time-provider-port
    port: 90
    targetPort: 90

---

apiVersion: v1
kind: Pod
metadata:
  name: time-provider
  labels:
    name: time-provider
spec:
  hostname: time-provider
  subdomain: default-subdomain
  containers:
  - image:  dworza/time-provider:latest
    command:
    name: time-provider


