apiVersion: v1
kind: Deployment
metadata:
  name: time-provider
spec:
  selector:
    matchLabels:
      run: time-provider
  replicas: 2
  template:
    metadata:
      labels:
        run: time-provider
    spec:
      containers:
      - name: time-provider
        image: time-provider
        ports:
        - containerPort: 80