apiVersion: v1
kind: Service
metadata:
  name: time-provider
  labels:
    name: time-provider
    context: java-project
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 9000
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: time-provider
    context: java-project
