apiVersion: v1
kind: Pod
metadata:
  name: time-provider
spec:
  replicas: 1
  containers:
    - name: time-provider
      image: time-provider
      ports:
        - containerPort: 9000
          hostPort: 90000