apiVersion: v1
kind: Pod
metadata:
  name: time-provider
spec:
  containers:
    - name: time-provider
      image: dworza/time-provider
      ports:
        - containerPort: 8086
          hostPort: 8086