apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-provider
spec:
  selector:
    matchLabels:
      run: time-provider
  replicas: 1
  template:
    metadata:
      labels:
        run: time-provider
    spec:
      containers:
      - name: time-provider
        image: dworza/time-provider:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 9001

---

apiVersion: v1
kind: Service
metadata:
  name: time-provider
  labels:
    run: time-provider
spec:
  ports:
  - port: 9001
    protocol: TCP
  selector:
    run: time-provider