apiVersion: apps/v1
  kind: Deployment
metadata:
    name: time-provider
spec:
    selector:
      matchLabels:
        app: time-provider
        tier: time-provider
        track: stable
    replicas: 1
    template:
      metadata:
        labels:
          app: time-provider
          tier: time-provider
          track: stable
      spec:
        containers:
          - name: time-provider
                  image: dworza/time-provider:latest
                  imagePullPolicy: "Always"
            ports:
              - name: http
                containerPort: 9000


  ---

kind: Service
apiVersion: v1
metadata:
    name: time-provider
spec:
    selector:
      app: java-project-gateway
      tier: java-project-gateway
    ports:
    - protocol: TCP
      port: 9000
      targetPort: http

