apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-provider
spec:
  selector:
    matchLabels:
      run: time-provider
  replicas: 1
  template:
    metadata:
      labels:
        run: time-provider
    spec:
      containers:
      - name: time-provider
        image: dworza/time-provider:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 9002

--
kind: Service
apiVersion: v1
metadata:
  name:  time-provider
spec:
  selector:
    app:  time-provider
  ports:
  - protocol: TCP
    port: 9002
    targetPort: 9002
  type: NodePort
