apiVersion: v1
kind: Pod
metadata:
  name: time-provider
spec:
#  hostNetwork: true
  containers:
    - name: time-provider
      image: dworza/time-provider
#       ports:
#        - containerPort: 9002