
apiVersion: v1
kind: Service
metadata:
  name: default-subdomain
spec:
  selector:
    name: busybox
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 90
    targetPort: 90

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  selector:
    matchLabels:
      app: busybox
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
        track: stable
    spec:
      hostname: busybox-1
      subdomain: default-subdomain
      containers:
      - image: dworza/time-provider:latest
        imagePullPolicy: "Always"

